### ISSUE TITLE
mysql8 support

### ISSUE THREAD

**Issue by jakemonO** [michaelruocco/embedded-mysql-plugin#14]
Any plans for MySQL8 support? I'd be happy to test a dev branch with that. wix-embedded-mysql supports 8.0.17

**Comment by michaelruocco** [comment]
Hi @jakemonO apologies I have not been giving this much attention recently. I have just updated all the dependencies and built and released version 2.1.11, so it should be available shortly. Please let me know if you have any issues when trying to use.

**Comment by jakemonO** [comment]
Will do. thanks. I was going to submit a PR...

**Comment by jakemonO** [comment]
I've tried a run with the MySQL8 build and I'm getting the following:
`Execution failed for task ':startEmbeddedMysql'.
> Command exited with error code: '1' and output: ''

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':startEmbeddedMysql'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:74)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.execute(DefaultTaskExecutionGraph.java:143)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:40)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:40)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:24)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:46)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:49)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:40)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:33)
        at org.gradle.initialization.DefaultGradleLauncher$ExecuteTasks.run(DefaultGradleLauncher.java:355)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.initialization.DefaultGradleLauncher.runTasks(DefaultGradleLauncher.java:219)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
        at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:124)
        at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:77)
        at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:74)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:154)
        at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:38)
        at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:96)
        at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:74)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.run(RunAsBuildOperationBuildActionRunner.java:50)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:44)
        at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:79)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:44)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:62)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:34)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:46)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:81)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.RuntimeException: Command exited with error code: '1' and output: ''
        at com.wix.mysql.distribution.setup.ProcessRunner.resolveException(ProcessRunner.java:53)
        at com.wix.mysql.distribution.setup.ProcessRunner.run(ProcessRunner.java:38)
        at com.wix.mysql.distribution.setup.Mysql8Initializer.apply(Mysql8Initializer.java:33)
        at com.wix.mysql.distribution.Setup.apply(Setup.java:24)
        at com.wix.mysql.MysqldExecutable.start(MysqldExecutable.java:36)
        at com.wix.mysql.MysqldExecutable.start(MysqldExecutable.java:15)
        at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:108)
        at com.wix.mysql.EmbeddedMysql.<init>(EmbeddedMysql.java:47)
        at com.wix.mysql.EmbeddedMysql$Builder.start(EmbeddedMysql.java:169)
        at com.wix.mysql.EmbeddedMysql$Builder$start.call(Unknown Source)
        at uk.co.mruoc.mysql.EmbeddedMysqlExtension.buildMysql(EmbeddedMysqlExtension.groovy:168)
        at uk.co.mruoc.mysql.EmbeddedMysqlExtension$buildMysql.call(Unknown Source)
        at uk.co.mruoc.mysql.StartEmbeddedMysqlTask.run(StartEmbeddedMysqlTask.groovy:18)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 111 more
`
I'm using mysql v8_0_17 (and jdbc driver: unittest_mysql_driver=com.mysql.cj.jdbc.Driver
unittest_mysql_connector=mysql-connector-java-8.0.18)

I haven't had a chance to inspect other than the wix embedded mysql process is returning an error code of 1 (that's not much to go by, I know)

If there's something obvious that jumps out at you that I've overlooked, I'd appreciate the advice.

TIA -Jake

**Comment by michaelruocco** [comment]
Hi @jakemonO,

Do you have a link to the project where you are having the issue? Or can you post an example of the build.gradle file please?

Thanks.

**Comment by jakemonO** [comment]
`buildscript {
    repositories {
        mavenCentral()
    }
}

plugins {
    id 'com.github.michaelruocco.embedded-mysql-plugin' version '2.1.11'
}

embeddedMysql {
    url = 'jdbc:mysql://localhost:3307/databaseName'
    username = 'user'
    password = ''
    version = 'v8_0_11'//'v8_latest'//'v5_6_24' //'v8_0_17'
}`

only works w/v5 version specified. I wonder, is it a JDBC driver issue? I've had to u/g the driver to work with MySQL8

**Comment by michaelruocco** [comment]
Is it possible for you to post the example project you are using so I can take a look?

I have managed to get it working with an very old project I had that was using it here and it seems to be working fine. The only difference I could spot is that you are not setting a password.

I do recall raising a bug / issue I ran into a while back when not using a password, details are here: https://github.com/wix/wix-embedded-mysql/issues/58. However the example I am using does seem to be using root with no password and it working fine. If you are interested the old project I am referring to is here: https://github.com/michaelruocco/web-template. It uses mysql as its backend, and I can run ./gradlew startWebApp and it works fine. I have also verified by using the latest version of mysql workbench to connect and verify too.

Additionally I have also updated the tests for the plugin to use mysql 8 explicitly too and those are also working and passing. https://github.com/michaelruocco/embedded-mysql-plugin/commit/39b43d4d85ec3cb9add32b8746d3bfa6a420325a.

As I said if you are happy to push an example project that recreates the error you are seeing I would be happy to take a further look.

**Comment by jakemonO** [comment]
The gradle.build file I posted in the previous message illustrates the issue is the example project. I uploaded the repo and sent you an invitation. TIA

**Comment by michaelruocco** [comment]
Thanks for the invite, I am wondering if there is some kind of local machine set up issue? I am able to run the project you shared fine using any of the commented out versions listed.

**Comment by jakemonO** [comment]
interesting.  I tried running it on a pristine linux box (popOS!) and got a libssl error. looks like this is catalogued here: https://github.com/airlift/testing-mysql-server/issues/16

I wonder if this impacts windows machines. I'll try it on a different windows machine later this evening & let you know

**Comment by michaelruocco** [comment]
Yeah maybe, I should have added my local machine is a Mac. I don’t have access to a windows machine to test on. I’ll see if I can give it a try on my Linux desktop later too if I get time.

**Comment by jakemonO** [comment]
My Windows machines that I tested on have this in their mysql err log:
`2019-12-01T17:03:01.120171Z 0 [System] [MY-013169] [Server] C:\projects\vantage\git-pristine\build\mysql-temp\mysql-8.0-9b6eb70f-cb2a-4fc8-b866-b29a4e7eb86f\bin\mysqld.exe (mysqld 8.0.17) initializing of server in progress as process 48888
2019-12-01T17:03:05.438603Z 0 [ERROR] [MY-010285] [Server] Failure to parse RSA private key (file exists): C:\projects\vantage\git-pristine\build\mysql-temp\mysql-8.0-9b6eb70f-cb2a-4fc8-b866-b29a4e7eb86f\data\\private_key.pem: error:0906D06C:PEM routines:PEM_read_bio:no start line
2019-12-01T17:03:05.445604Z 0 [ERROR] [MY-010119] [Server] Aborting
2019-12-01T17:03:06.203680Z 0 [System] [MY-010910] [Server] C:\projects\vantage\git-pristine\build\mysql-temp\mysql-8.0-9b6eb70f-cb2a-4fc8-b866-b29a4e7eb86f\bin\mysqld.exe: Shutdown complete (mysqld 8.0.17)  MySQL Community Server - GPL.`

**Comment by jakemonO** [comment]
I can't even find the equivalent error file on my Linux test box. I have confirmed that the stated dependency of `libaio1` (from wix readme) is installed on the Linux box

**Comment by jakemonO** [comment]
sigh, this is getting complicated. When I run this on a jenkins build server using the custom cache path to point to a mysql 8 download I pull from an internal artifactory repo (this is how I used it w/mysql 5.7) The wix stuff tries to find a file with a .xz extension for some reason. Even when I unzip the .gz file and reencode it as an xz it fails validation. No idea why its looking for an .xz file. So now I have 3 schenarios that I can;t get MySQL8 to work on:
1. windows
2. vanilla Linux
3. Jenkins/Linux

Gonna need to do some more digging in my spare time to untangle all this.

**Comment by jakemonO** [comment]
need to retract the xz file issue. That was my oversight, I didn't see the new extension in the download and I have to spoof dev.mysql.com download host in my build. If I can get the libssl1.0 issues worked out (I know, it's a wix-embedded-mysql prereq, still having some issues) I will consider this a successful MySQL8- supporting plugin for my needs. Windows is a mystery, still, though

**Comment by michaelruocco** [comment]
Hi @jakemonO, are you still having issues with this or is your problem resolved now?

**Comment by jakemonO** [comment]
well, I'm having the upstream issues and I still can;t get it working on windows either, but the specific technical issue of having the MySQL8 constants in your build are fixed.
